### ISSUE TITLE
Move Computing Infrastructure from GCP to Render

### ISSUE THREAD

**Issue by brodyu** [brodyu/celery_backtester#14]
# Move Cloud Platforms

## Task
Move the backtesting infrastructure from GCP to Render.

## Actions
- [x] Create using Render's IaC tools. 
- [x] Recreate computing engine (Flask, Celery, Redis)
- [x] Need a PostgreSQL database for storing backtesting metadata
- [x] Allow connection to existing data warehouse
